Add Duo Passcode support for both traditional and universal prompt
venth/aws-adfs pull request #353
Opened 2022-10-22 03:42 UTC by trav-c

* Added support for the Passcode method to both duo traditional and universal prompts
* Extended --duo-factor and --duo-device to support from duo universal prompt to also include duo traditional prompt
* Added pattern matching to make --duo-factor more forgiving (eg `--duo-factor WebAuthn` is now equivalent to `--duo-factor "WebAuthn Security Key"` and `--duo-factor Push` is equivalent to `--duo-factor "Duo Push"` etc).  Unmatched / unrecognized factors are still passed through as originally specified, and the original, full versions of the factor names are also still supported.

I have tested this with Passcode, Push, Phone Call and Webauthn for both the Universal and Traditional prompt, Passcodes work properly for both hardware (TOTP) tokens and Bypass codes, however as yet the 'sms' factor is not fully supported.  You can initiate an SMS (which will send the message, but then fail), then use the code(s) from the SMS message with the passcode method though.

This resolves #162

2022-10-24 09:42 UTC, pdecat requested changes
Thanks for this awesome addition!

Left a few minor comments, but looks good to me!

2022-10-24 09:42 UTC, pdecat commented on aws_adfs/login.py
> +    help=f'Use a specific Duo factor, overriding the default one configured server side. Known Duo factors that can be used with aws-adfs are "{DUO_UNIVERSAL_PROMPT_FACTOR_DUO_PUSH}", "{DUO_UNIVERSAL
Isn't the `Only supported with Duo Universal Prompt` part no longer valid with this PR too?
```suggestion
    help=f'Use a specific Duo factor, overriding the default one configured server side. Known Duo factors that can be used with aws-adfs are "{DUO_UNIVERSAL_PROMPT_FACTOR_DUO_PUSH}", "{DUO_UNIVERSAL_PROMPT_FACTOR_PHONE_CALL}", "{DUO_UNIVERSAL_PROMPT_FACTOR_WEBAUTHN}" and "{DUO_UNIVERSAL_PROMPT_FACTOR_PASSCODE}".',
```

2022-10-26 03:24 UTC, trav-c commented
I've applied the proposed updates, not sure what happened with the help, since I did make that change, but must not have pushed it before opening my PR or something.  Otherwise noted on the ordering of the constants.

2022-10-26 07:27 UTC, pdecat approved these changes
LGTM, thanks again!

2022-10-26 07:27 UTC, merged

2022-10-26 07:53 UTC, pdecat commented
Released in https://github.com/venth/aws-adfs/releases/tag/v2.6.0

2022-10-26 09:55 UTC, pdecat commented
As I anticipated this PR also adds support for hardware tokens that generate HOTP codes (e.g. RSA).
I don't have one, but a colleague confirmed this to me. A PR is coming to explicitly mention this.